<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ESCenter</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Themes\Philips E-SCenter Icon.ico</ApplicationIcon>

	  <Company>E-SCenter</Company>
	  <Authors>Mohamad Sukar</Authors>
	  <Product>E-SCenter</Product>
	  <Description>Electronics Service Center Management App</Description>
	  <Copyright>© 2026 Mohamad Sukar</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\Icons\New\**" />
    <Compile Remove="ESCenter\**" />
    <EmbeddedResource Remove="Assets\Icons\New\**" />
    <EmbeddedResource Remove="ESCenter\**" />
    <None Remove="Assets\Icons\New\**" />
    <None Remove="ESCenter\**" />
    <Page Remove="Assets\Icons\New\**" />
    <Page Remove="ESCenter\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Icons\Add.png" />
    <None Remove="Assets\Icons\AddressBook.png" />
    <None Remove="Assets\Icons\add_task.png" />
    <None Remove="Assets\Icons\AdminTitle.png" />
    <None Remove="Assets\Icons\AI Select.png" />
    <None Remove="Assets\Icons\Al-Baraka Logo.ico" />
    <None Remove="Assets\Icons\AlBaraka.png" />
    <None Remove="Assets\Icons\AllList.png" />
    <None Remove="Assets\Icons\amend.png" />
    <None Remove="Assets\Icons\aod_watch.png" />
    <None Remove="Assets\Icons\area_chart.png" />
    <None Remove="Assets\Icons\arming_countdown.png" />
    <None Remove="Assets\Icons\azm.png" />
    <None Remove="Assets\Icons\Battery_android_frame_shield.png" />
    <None Remove="Assets\Icons\battery_android_shield.png" />
    <None Remove="Assets\Icons\BoardMod.png" />
    <None Remove="Assets\Icons\boneyard.png" />
    <None Remove="Assets\Icons\Brand.png" />
    <None Remove="Assets\Icons\cadence.png" />
    <None Remove="Assets\Icons\Call Assist.png" />
    <None Remove="Assets\Icons\cancel.png" />
    <None Remove="Assets\Icons\CategoryList.png" />
    <None Remove="Assets\Icons\Charts.png" />
    <None Remove="Assets\Icons\Chat Assist.png" />
    <None Remove="Assets\Icons\Chat Assist2.png" />
    <None Remove="Assets\Icons\Circle to Search.png" />
    <None Remove="Assets\Icons\Clear.png" />
    <None Remove="Assets\Icons\clear_all.png" />
    <None Remove="Assets\Icons\click-to search.png" />
    <None Remove="Assets\Icons\ClientName.png" />
    <None Remove="Assets\Icons\clock_arrow_down.png" />
    <None Remove="Assets\Icons\component.png" />
    <None Remove="Assets\Icons\ContactMethod.png" />
    <None Remove="Assets\Icons\counter0.png" />
    <None Remove="Assets\Icons\cruelty_free_35dp.png" />
    <None Remove="Assets\Icons\Dashboard.png" />
    <None Remove="Assets\Icons\database.png" />
    <None Remove="Assets\Icons\DatabaseCreate.png" />
    <None Remove="Assets\Icons\DatabaseEdit.png" />
    <None Remove="Assets\Icons\DatabaseReset.png" />
    <None Remove="Assets\Icons\database_upload.png" />
    <None Remove="Assets\Icons\data_array.png" />
    <None Remove="Assets\Icons\Delete-Close Title.png" />
    <None Remove="Assets\Icons\deployed_code_alert - Copy.png" />
    <None Remove="Assets\Icons\deployed_code_alert.png" />
    <None Remove="Assets\Icons\DeviceModel.png" />
    <None Remove="Assets\Icons\devicesType.png" />
    <None Remove="Assets\Icons\devices_wearables - Copy.png" />
    <None Remove="Assets\Icons\devices_wearables.png" />
    <None Remove="Assets\Icons\devices_wearables_35dp - Copy.png" />
    <None Remove="Assets\Icons\devices_wearables_35dp.png" />
    <None Remove="Assets\Icons\DmgHistory1Title.png" />
    <None Remove="Assets\Icons\DmgHistoryTitle.png" />
    <None Remove="Assets\Icons\do_not_disturb.png" />
    <None Remove="Assets\Icons\Drawing Assist.png" />
    <None Remove="Assets\Icons\edit_audio.png" />
    <None Remove="Assets\Icons\edit_document.png" />
    <None Remove="Assets\Icons\ESC-ID Title.png" />
    <None Remove="Assets\Icons\ESC-ID Title1.png" />
    <None Remove="Assets\Icons\EstimatedCost.png" />
    <None Remove="Assets\Icons\expand_circle_up - Copy.png" />
    <None Remove="Assets\Icons\expand_circle_up.png" />
    <None Remove="Assets\Icons\filter_vintage.png" />
    <None Remove="Assets\Icons\FinalCost.png" />
    <None Remove="Assets\Icons\FinalCost1.png" />
    <None Remove="Assets\Icons\flutter - Copy.png" />
    <None Remove="Assets\Icons\flutter.png" />
    <None Remove="Assets\Icons\foot_bones.png" />
    <None Remove="Assets\Icons\frame_reload.png" />
    <None Remove="Assets\Icons\galaxy-ai.png" />
    <None Remove="Assets\Icons\galaxy-ai1.png" />
    <None Remove="Assets\Icons\galaxy-ai2.png" />
    <None Remove="Assets\Icons\galaxy-ai3.png" />
    <None Remove="Assets\Icons\galaxy-ai4.png" />
    <None Remove="Assets\Icons\galaxy-ai5.png" />
    <None Remove="Assets\Icons\galaxy-ai6.png" />
    <None Remove="Assets\Icons\GalaxyAiSearch.png" />
    <None Remove="Assets\Icons\google-toolbar.png" />
    <None Remove="Assets\Icons\Guard.png" />
    <None Remove="Assets\Icons\ID Title.png" />
    <None Remove="Assets\Icons\identity.png" />
    <None Remove="Assets\Icons\id_card - Copy.png" />
    <None Remove="Assets\Icons\id_card.png" />
    <None Remove="Assets\Icons\Inevntory.png" />
    <None Remove="Assets\Icons\inventory.png" />
    <None Remove="Assets\Icons\join.png" />
    <None Remove="Assets\Icons\List.png" />
    <None Remove="Assets\Icons\list_alt_add - Copy.png" />
    <None Remove="Assets\Icons\list_alt_add.png" />
    <None Remove="Assets\Icons\local_activity.png" />
    <None Remove="Assets\Icons\LowStock.png" />
    <None Remove="Assets\Icons\low_priority.png" />
    <None Remove="Assets\Icons\mobile_3_35dp - Copy.png" />
    <None Remove="Assets\Icons\mobile_3_35dp.png" />
    <None Remove="Assets\Icons\mobile_code_35dp.png" />
    <None Remove="Assets\Icons\mobile_wrench_24dp.png" />
    <None Remove="Assets\Icons\mobile_wrench_35dp.png" />
    <None Remove="Assets\Icons\Model.png" />
    <None Remove="Assets\Icons\Note Assist.png" />
    <None Remove="Assets\Icons\Notes.png" />
    <None Remove="Assets\Icons\offline_pin_30dp.png" />
    <None Remove="Assets\Icons\OutStock.png" />
    <None Remove="Assets\Icons\Parts.png" />
    <None Remove="Assets\Icons\PartsUsed.png" />
    <None Remove="Assets\Icons\Play AI.png" />
    <None Remove="Assets\Icons\power_settings_circle_30dp.png" />
    <None Remove="Assets\Icons\preliminary.png" />
    <None Remove="Assets\Icons\price_check_24dp.png" />
    <None Remove="Assets\Icons\Priority.png" />
    <None Remove="Assets\Icons\priority_30dp.png" />
    <None Remove="Assets\Icons\priority_high_24dp.png" />
    <None Remove="Assets\Icons\ProblemDescription.png" />
    <None Remove="Assets\Icons\process_chart_30dp.png" />
    <None Remove="Assets\Icons\QR.png" />
    <None Remove="Assets\Icons\ReadyToPick.png" />
    <None Remove="Assets\Icons\reboot_galaxy_s10.png" />
    <None Remove="Assets\Icons\recycling.png" />
    <None Remove="Assets\Icons\Refresh.png" />
    <None Remove="Assets\Icons\regular_expression.png" />
    <None Remove="Assets\Icons\ReopenTitle.png" />
    <None Remove="Assets\Icons\RepairOnWarranty.png" />
    <None Remove="Assets\Icons\RepairStatus.png" />
    <None Remove="Assets\Icons\ResetSTG.png" />
    <None Remove="Assets\Icons\RootCause.png" />
    <None Remove="Assets\Icons\safety_check.png" />
    <None Remove="Assets\Icons\Save.png" />
    <None Remove="Assets\Icons\saved_search.png" />
    <None Remove="Assets\Icons\search-engines.png" />
    <None Remove="Assets\Icons\search_insights.png" />
    <None Remove="Assets\Icons\segment.png" />
    <None Remove="Assets\Icons\Serial.png" />
    <None Remove="Assets\Icons\SerialTitle.png" />
    <None Remove="Assets\Icons\Settings.png" />
    <None Remove="Assets\Icons\settings1.png" />
    <None Remove="Assets\Icons\Shutdown_galaxy_s10.png" />
    <None Remove="Assets\Icons\stacks_35dp.png" />
    <None Remove="Assets\Icons\Statistics.png" />
    <None Remove="Assets\Icons\TickClosed.png" />
    <None Remove="Assets\Icons\Tickets.png" />
    <None Remove="Assets\Icons\token.png" />
    <None Remove="Assets\Icons\translate.png" />
    <None Remove="Assets\Icons\Unassigned.png" />
    <None Remove="Assets\Icons\verified.png" />
    <None Remove="Assets\Icons\warning_24d.png" />
    <None Remove="Assets\Icons\Warranty.png" />
    <None Remove="Assets\Icons\Warranty1.png" />
    <None Remove="Assets\Icons\watch_lock_24dp.png" />
    <None Remove="Assets\Icons\watch_screentime_35dp.png" />
    <None Remove="Themes\Statistics Resurces.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Themes\Philips E-SCenter Icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Core" Version="2.1.0" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.1.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
	  
  </ItemGroup>
	
    <ItemGroup>
	<PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
	</ItemGroup>
	
  <ItemGroup>
    <Resource Include="Assets\Icons\Add.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\AddressBook.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\AdminTitle.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\AI Select.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Al-Baraka Logo.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\AlBaraka.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\AllList.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\aod_watch.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\arming_countdown.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Battery_android_frame_shield.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\battery_android_shield.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\BoardMod.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\boneyard.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Brand.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\cadence.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Call Assist.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\CategoryList.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Charts.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Chat Assist.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Chat Assist2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Circle to Search.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Clear.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\click-to search.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Dashboard.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\database.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\DatabaseCreate.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\DatabaseEdit.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\DatabaseReset.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\database_upload.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\data_array.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Delete-Close Title.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\deployed_code_alert.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\devicesType.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\devices_wearables.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\DmgHistory1Title.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\DmgHistoryTitle.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\do_not_disturb.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Drawing Assist.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\edit_audio.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\ESC-ID Title.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\ESC-ID Title1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\EstimatedCost.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\filter_vintage.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\FinalCost.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\galaxy-ai1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\galaxy-ai2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\galaxy-ai3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\galaxy-ai4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\galaxy-ai5.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\galaxy-ai6.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\GalaxyAiSearch.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\google-toolbar.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Guard.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\ID Title.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Inevntory.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\List.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\LowStock.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\mobile_code_35dp.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\mobile_wrench_24dp.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Model.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Note Assist.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\OutStock.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Parts.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\PartsUsed.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Play AI.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\preliminary.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\price_check_24dp.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Priority.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\ProblemDescription.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\QR.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\ReadyToPick.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\reboot_galaxy_s10.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Refresh.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\regular_expression.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\ReopenTitle.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\RepairOnWarranty.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\RepairStatus.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\ResetSTG.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\RootCause.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\safety_check.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Save.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\search-engines.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\SerialTitle.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Settings.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\settings1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Shutdown_galaxy_s10.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Statistics.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\TickClosed.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Tickets.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\token.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\translate.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Unassigned.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\verified.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Warranty.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\Warranty1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\watch_lock_24dp.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\watch_screentime_35dp.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
